_BASE_: Base-BMask-R-CNN-FPN.yaml
MODEL:
  WEIGHTS: detectron2://ImageNetPretrained/MSRA/R-50.pkl
  MASK_ON: true
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 12
  RETINANET:
    NUM_CLASSES: 12
  SEM_SEG_HEAD:
    NUM_CLASSES: 12
INPUT:
  MIN_SIZE_TRAIN: (800, 1400)
  MIN_SIZE_TRAIN_SAMPLING: 'range'
  MAX_SIZE_TRAIN: 1600
  MIN_SIZE_TEST: 1200
  MAX_SIZE_TEST: 1200
TEST:
  EVAL_PERIOD: 1120
  AUG:
    ENABLED: true
    MIN_SIZES: (1200,)
    MAX_SIZE: 1200
    FLIP: false
DATASETS:
  TRAIN: ("my_dataset_train",)
  TEST: ("my_dataset_val",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  STEPS: (9000, 12000)
  MAX_ITER: 60000
  WEIGHT_DECAY: 0.00001
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 1120
OUTPUT_DIR: "./outputs"